### ISSUE TITLE
bobでneovimのバージョンを管理する

### ISSUE THREAD

**Issue by mimikun** [mimikun/dotfiles#483]
https://github.com/MordechaiHadad/bob

neovim HEADを使うと大量に非推奨警告が出てくる。
v0.11対応しているプラグインはまだ少ない。
プラグイン側が対応するまで、v0.10を使いたい。

Linuxはmiseで、Windowsはscoopでインストールしている。

miseだとバージョン管理が若干辛い。
scoopはそもそもバージョン管理のソフトではなさそう。

### TODO 

影響を受けるもの

- [x] update_mise
- [x] nyagos
    - [x] alias.lua
    - [x] env.lua
- [x] vup
- [x] `bob/config.toml` template化
    - [x] Work-Windows
    - [x] Home-Windows
- [x] linux_cargo_package_list.txt
- [x] windows_cargo_package_list.txt

**Comment by mimikun** [comment]
- [ ] update_mise
- [x] nyagos
    - [x] alias.lua
    - [x] env.lua
- [ ] vup

**Comment by mimikun** [comment]
scoopもバージョン管理できることがわかった。

**Comment by mimikun** [comment]
でもmiseとscoopで別々管理はやはり面倒なので統一したい。あと面白そう。

**Comment by mimikun** [comment]
Windowsのconfig.tomlで `$env:USERPROFILE` が使えるのか気になる。使えればtemplateは必要ない。

**Comment by mimikun** [comment]
> Windowsのconfig.tomlで `$env:USERPROFILE` が使えるのか気になる。使えればtemplateは必要ない。

使えなかった。

**Comment by mimikun** [comment]
Windowsではheadをビルドできないものと考えたほうが良さそうだった。
めっちゃ警告が出る。

**Comment by mimikun** [comment]
結果的にビルドすらできなかった。終わり
